### ISSUE TITLE
main page

### ISSUE THREAD

**Issue by mohbusaidy** [mohbusaidy/Capstone-Project#1]
## Value Proposition

As a user 
I want to see product cards with prices 
to be able to choose one of them. 

## Description

<img width="290" alt="Bildschirmfoto 2022-07-20 um 16 58 46" src="https://user-images.githubusercontent.com/104504053/180015039-6622a8e6-d072-42bf-b81b-3ad60085172d.png">

## Acceptance Criteria

- [ ] 1 slider scroll able (3x3)
- [ ] the prices are shown for each product 
- [ ] the headline category above the product cards

## Tasks

(for developers team)

- [ ] create global design
- [ ] Header as a styled component 
- [ ] Product chart with little cards init vertical scroll able  
- [ ] write test for scroll bar  
- [ ] product component as little cards with images and prices 
- [ ] for each component storybooks 
- [ ] db 30 example product with prices and images

**Comment by actyvystom** [comment]
Hi Mo, 
I like this first one :)
Some comments to consider: 
- Your value proposition is a bit confusing and does not follow the expected basic format... try thinking (and describing) from a user point of view in terms of _needed functionality_ to _achieve a goal_, this would probably lead you to a very first user story which e.g. could be described like this:   

_As a user, I want to start my journey on a page where I can choose a criteria/category of products 
to be able to find my favorite category._

Try to get as precise as possible in describing the tasks, e.g. 
- add specific test tasks, write tests for which component?
-  create a horizontal slider component (the bar itself won't suffice, I guess ;)) 
- think of adding storybook usage (which component, etc.)

**Comment by chris-yooo** [comment]
Hey Mo,

after we have completely rewritten your user story today i think i can give you the green hook right away - but i would like thomas or paul to look over it again so they can put the 2nd green hook :)

**Comment by julialoeschel** [comment]
Hey Mo, 
good Job there!

I have little trouble to understand the 3 sliders. 
Are that the same sliders? can we break it down to only one slider in the first Userstory (I suggest to to that)?  Are you mocking your data? 

other than that - great 🐜  :octocat:
