### ISSUE TITLE
filter sort function

### ISSUE THREAD

**Issue by mohbusaidy** [mohbusaidy/Capstone-Project#2]
## Value Proposition

As a user,
I want to filter/sort products,
to be able to display them together or sorted. 

## Description

Scribble / design or text
<img width="200px" alt="Bildschirmfoto 2022-07-20 um 17 09 06" src="https://user-images.githubusercontent.com/104504053/180017576-489c560f-01c8-45d4-afe4-66da15d6abc3.png">

## Acceptance Criteria

- [ ] filter function camera
- [ ] filter function lenses 
- [ ] sort function cheapest 
- [ ] sort function most expensive 

## Tasks

(for developers team)

- [ ] create filter drop-down menu   
- [ ] filter for only body cameras/ only lenses/ 
- [ ] sort function cheapest at the top/ most expensive at the top 
- [ ] update db.js

**Comment by actyvystom** [comment]
Hi Mo,
I guess my comments on your [first user story](https://github.com/mohbusaidy/Capstone-Project/issues/1) will affect this one, too... Please rework the first one and see if you can apply some takeaways of the first one also here ;)

**Comment by chris-yooo** [comment]
mo this morning we have your first user story completely rebuilt :D

I would write:

as a user
i want to filter products
to be able to display them together

the please customize is stupid but has the advantage to capture it much faster instead of searching in a line for to be able to...

----

i would like to have a scribbl of the filter function, i don't know now how you include that :=)

and under acceptence criteria you can leave the default filter for the moment. rather take first of all the product data after the order in which you have stored them. say you have your arrays with fake data populated, then they are also in the order to see :)

in next, the filter they you have, "cameras - Only lenses - cheapest" yalala tralala -> that is an acceptence critera... btw where is your acceptence criteria ??

and you want to filter with use states ? or the map function in javasc. ?


this US from u are 99% different as the story from morning my lovely

chris

**Comment by chris-yooo** [comment]
after we've made the changes i love it :) nothing stands in the way of the green check mark

**Comment by PReichetanz** [comment]
Hi Mo,

looks good so far!
Just one question: How do I select whether I want to filter or sort the products? In your wireframe, I only can see a selection for sorting the products; how do I filter them?

It might be a good idea to separate sorting and filtering into two separate user stories, but that's up to you.
