### ISSUE TITLE
bookmark function

### ISSUE THREAD

**Issue by mohbusaidy** [mohbusaidy/Capstone-Project#3]
## Value Proposition

As a user
I want to save my favorite products,
to be able to remember them. 

## Description

<img width="376" alt="Bildschirmfoto 2022-07-20 um 17 23 00" src="https://user-images.githubusercontent.com/104504053/180020938-5b14ba87-bd54-4561-bbdd-aaa3194227b0.png">

## Acceptance Criteria

- [ ] I can add a favorite by clicking the heart button
- [ ] every product card are displayed in scroll able horizontal bottom slider 
- [ ] Favorites can be removed by clicking the heart icon again  

## Tasks

(for developers team)

- [ ] create favorite slider at the bottom 
- [ ] bookmark saving function for every product card   
- [ ]  implement heart icon  
- [ ] bookmarked product cards are displayed in scroll able horizontal bottom slider
- [ ] update storybook 
- [ ] update db.js 
- [ ] write test

**Comment by actyvystom** [comment]
Hi Mo, 
as also commented on the mohbusaidy/Capstone-Project#1 and mohbusaidy/Capstone-Project#2, please try to stick to the correct format in describing the value proposition (and also the title of the issue). Please try to rework the first one and adapt useful changes to this one, too.

Some comments on the task list: 
- You can try to specify more detail for the tasks, e.g. which components to create and set up, add storybook components, how are you going to place specs on the popup picture screen etc.

**Comment by chris-yooo** [comment]
hey mo ty for updating ur mohbusaidy/Capstone-Project#2 story -> legit

to ur 3rd story:

here I would wish that you already post real pictures in your description.

And don't you want to build a fourth slider with your favorite products at the bottom ?


edit:

nice work

**Comment by PReichetanz** [comment]
Hi Mo,

a really good start for your user story! 🎉

💬 Just two things which came to my mind:

- Please rephrase the title of the story; "user story 3" is not a good one since you cannot know whether this story might be build earlier or later.

- Where is this separate page for the bookmarks? I guess you implement it together with this story, so how do I get there and how do I get back? Have a look at the user stories we have written for the jokes app where we implemented a bookmark as well ;)

**Comment by chris-yooo** [comment]
we've changed the product grid in first story and you renamed this one you doesn't need a seperate page for bookmarks ^^

great work

<3

**Comment by PReichetanz** [comment]
Hi Mo,

a really good start for your user story! 🎉

💬 Let's discuss one issue which came to my mind while reading:

## Acceptance Criteria
- I guess the second one should be "bookmarked product cards are displayed in scroll able horizontal bottom slider", shouldn't it?

**Comment by mohbusaidy** [comment]
yes exactly that i will update it. Thanks for clarifying!
